name: Checkout Practice

on:
  push:

jobs:
  explore:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show current directory
        run: pwd

      - name: Show the files like tree
        run: tree

      - name: List repository files
        run: ls -la

      - name: Show Git status
        run: git status
