name: workflow_dispatch


on:
  workflow_dispatch:

jobs:
  manually:
    runs-on: ubuntu-latest

    steps:
      - name: manually started
        run: echo "I manually started this workflow"

      - name: manually
        run: echo "This workflow was started manually"

      - name: Learning GitHub Actions
        run: echo "Learning GitHub Actions step by step"
