name: practice

on:
 push:

jobs:
  practice:
   runs-on: ubuntu-latest

   steps:

    - name: Actions Checkout
      uses: actions/checkout@v4

    - name: Current directory
      run: pwd

    - name: List Files
      run: ls -la

    - name: Git version
      run: git --version

    - name: Python Version
      run: python --version

    - name: Learning message
      run: |
        echo "I am learning GitHub Actions"
        whoami
        uname -a
